/* cubby editor v0.1.0 (https://github.com/patsissons/cubby) */
(()=>{var u=typeof window<"u"&&window.cubby||null,g=u?.CubbyError,U=u?.toCubbyError,I=u?.escapeHtml,O=u?.sanitizeUrl,A=u?.injectStyle,z=u?.ensureTokens,$=u?.widget;function D(a,...b){let t=[];u?.CubbyError||t.push("core.js");for(let c of b)u?.[c]||t.push(`${c}.js`);return t.length?(console.error(`[cubby] ${a} needs ${t.join(" + ")} loaded first. Tag order is core.js, platform.js, markdown.js, editor.js, then your app.js \u2014 all defer.`),null):u}var C={"image/png":"png","image/jpeg":"jpg","image/gif":"gif","image/webp":"webp"};function N(a){return function(t,c={}){if(typeof document>"u")throw new g("bad_request","attachImageUpload requires a DOM");let i=c.pathPrefix||"uploads/",y=c.maxBytes||10*1024*1024,f=c.onUploadStart||(()=>{}),j=c.onUpload||(()=>{}),h=c.onError||(r=>console.error("[cubby] image upload failed:",r));function p(){t.dispatchEvent(new Event("input",{bubbles:!0}))}function o(r){t.setRangeText(r,t.selectionStart,t.selectionEnd,"end"),p()}function l(r,e){let n=t.value.indexOf(r);return n===-1?!1:(t.setRangeText(e,n,n+r.length,"preserve"),p(),!0)}async function m(r){let e=a.identity?.user;if(!e){h(new g("auth_required","sign in to upload images"));return}if(r.size>y){h(new g("file_too_large",`image exceeds ${y} bytes`));return}let n=C[r.type],x=Date.now().toString(36)+Math.random().toString(36).slice(2,8),d=(r.name||`image.${n}`).replace(/[[\]()\n\r]/g,""),S=`![Uploading ${d}\u2026](cubby-upload:${x})`,s=`${i}${e.id}/${x}.${n}`;o(S),f({name:d,path:s});try{let T=(await a.fs.write(s,r)).url||await a.fs.url(s);l(S,`![${d}](${T})`),j({name:d,path:s,url:T})}catch(k){l(S,""),h(U(k,"upload_failed"))}}function v(r){let e=Array.from(r.clipboardData?.items||[]).filter(n=>n.kind==="file"&&C[n.type]).map(n=>n.getAsFile()).filter(Boolean);if(e.length){r.preventDefault();for(let n of e)m(n)}}function w(r){r.preventDefault()}function E(r){let e=Array.from(r.dataTransfer?.files||[]).filter(n=>C[n.type]);if(e.length){r.preventDefault();for(let n of e)m(n)}}return t.addEventListener("paste",v),t.addEventListener("dragover",w),t.addEventListener("drop",E),()=>{t.removeEventListener("paste",v),t.removeEventListener("dragover",w),t.removeEventListener("drop",E)}}}var _=`
.cubby-md-editor { border: 1px solid var(--border, #c8c2ba); border-radius: 8px; overflow: hidden; }
/* explicit display rules would otherwise defeat the hidden attribute */
.cubby-md-input[hidden], .cubby-md-preview[hidden] { display: none; }
.cubby-md-tabs { display: flex; gap: 0.25rem; padding: 0.4rem 0.5rem 0; border-bottom: 1px solid var(--border, #c8c2ba); }
.cubby-md-tab { border: 0; background: none; color: var(--muted, #6f6b66); font: inherit; padding: 0.35rem 0.75rem; cursor: pointer; border-radius: 6px 6px 0 0; }
.cubby-md-tab[aria-selected="true"] { color: inherit; font-weight: 600; box-shadow: inset 0 -2px 0 var(--accent, #4a7dbd); }
.cubby-md-input { display: block; width: 100%; border: 0; outline: none; padding: 0.75rem; background: none; color: inherit; font: 0.9em/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; resize: vertical; min-height: 8rem; }
.cubby-md-preview { padding: 0.75rem; }
.cubby-md-empty { color: var(--muted, #6f6b66); }
.cubby-md-split { display: grid; grid-template-columns: 1fr 1fr; }
.cubby-md-split .cubby-md-preview { border-left: 1px solid var(--border, #c8c2ba); overflow-y: auto; }
@media (max-width: 40rem) {
  .cubby-md-split { grid-template-columns: 1fr; }
  .cubby-md-split .cubby-md-preview { border-left: 0; border-top: 1px solid var(--border, #c8c2ba); }
}
`;function M(){A("editor",_)}function q(a,b){return $("editor",(t,c,i={})=>{if(typeof document>"u")throw new g("bad_request","editor requires a DOM");let y=a.markdown;if(!y)throw new g("bad_request","the editor needs /js/markdown.js loaded before it");y.injectStyles(),M();let f=i.preview===!1?"none":i.preview==="split"?"split":"tabs",j=i.previewDebounceMs??150,h=i.onChange||(()=>{}),p=document.createElement("div");p.className="cubby-md-editor";let o=document.createElement("textarea");o.className="cubby-md-input",o.rows=i.rows||8,o.value=i.value||"",i.placeholder&&(o.placeholder=i.placeholder);let l=document.createElement("div");l.className="cubby-md-preview cubby-markdown";function m(){let e=o.value;l.innerHTML=e.trim()?y.render(e,{linkTarget:i.linkTarget}):'<p class="cubby-md-empty">Nothing to preview</p>'}let v=null,w=null;if(f==="tabs"){let e=document.createElement("div");e.className="cubby-md-tabs",e.setAttribute("role","tablist");let n=(d,S)=>{let s=document.createElement("button");return s.type="button",s.className="cubby-md-tab",s.setAttribute("role","tab"),s.setAttribute("aria-selected",String(S)),s.textContent=d,e.appendChild(s),s};v=n("Write",!0),w=n("Preview",!1);let x=d=>{v.setAttribute("aria-selected",String(!d)),w.setAttribute("aria-selected",String(d)),o.hidden=d,l.hidden=!d,d?m():o.focus()};t.on(v,"click",()=>x(!1)),t.on(w,"click",()=>x(!0)),l.hidden=!0,p.append(e,o,l)}else if(f==="split"){let e=document.createElement("div");e.className="cubby-md-split",e.append(o,l),p.appendChild(e),m()}else p.appendChild(o);let E=null;t.on(o,"input",()=>{h(o.value),f==="split"&&(clearTimeout(E),E=setTimeout(m,j))}),t.own(()=>clearTimeout(E));let r=[];return i.upload!==!1&&a.hasPlatform?.()&&t.own(b(o,{...i.upload||{},onUploadStart:i.onUploadStart,onUpload:e=>{r.push(e),i.onUpload?.(e)},onError:i.onError})),c.replaceChildren(p),t.own(()=>p.remove()),{get value(){return o.value},set value(e){this.setValue(e)},setValue(e){o.value=String(e),h(o.value),(f==="split"||f==="tabs"&&!l.hidden)&&m()},textarea:o,preview:l,images:r,focus(){o.focus()},refresh(){m()}}})}function L(a){let b=N(a),t=q(a,b);return t.attachImageUpload=b,t}if(typeof window<"u"){let a=D("editor.js","markdown");a&&(a.editor=L(a))}})();
